:jbake-title: Install docToolchain
include::_config.adoc[]

== Welcome!

Nice to meet you.
Glad that you want to learn more about using docToolchain.
Start by installing what you need.

The following steps guide you through the installation.
If you encounter problems, create a https://github.com/docToolchain/docToolchain/issues[GitHub issue] and the community will help you.

=== Prerequisites

* *Java 17* or newer
* *git*

=== 1. Get the Wrapper Scripts

.Linux / macOS / WSL2
[role='primary']
--
[source, bash]
----
cd <your project>
curl -Lo dtcw https://doctoolchain.org/dtcw
curl -Lo dtcw4 https://doctoolchain.org/dtcw4
chmod +x dtcw dtcw4
----
--

.Windows with Powershell
[role='secondary']
--
[source, powershell]
----
cd <your project>
Invoke-WebRequest doctoolchain.org/dtcw -Outfile dtcw
Invoke-WebRequest doctoolchain.org/dtcw.ps1 -Outfile dtcw.ps1
----
--

=== 2. Install docToolchain

[source, bash]
----
./dtcw local install java        # if Java is not installed
./dtcw4 local install doctoolchain
----

=== 3. Try It Out

[source, bash]
----
./dtcw4 tasks
----

This lists all available tasks.

=== Problems & solutions

==== `dtcw` doesn't run

You might get an error like:

[source]
----
./dtcw: line 1: syntax error near unexpected token `newline'
./dtcw: line 1: `<!DOCTYPE html>'
----

This means the wrapper didn't download correctly (an HTML page was downloaded instead).
Please redownload the wrapper.

==== Docker throws an error with `dtcw`

On Windows you might get:

[source]
----
Error response from daemon: user declined directory sharing C:\Users\path_to_my_folder
----

Go to Docker Dashboard -> Settings -> Resources -> File Sharing. Add the required folder and hit Apply & Restart.
