:jbake-rightColumnHtml: <a href="single-page.html"><i class="fa fa-file fa-fw"></i> View single page</a>
:filename: 010_manual/30_config.adoc

= Configuration

include::../_feedback.adoc[]

This appendix covers all configuration introduced by docToolchain.
AsciiDoc, AsciiDoctor, Gradle and other tools and libraries used know of more configuration settings and you can read about those in the corresponding documentation.

== `mainConfigFile` and `docDir`

docToolchain should be easy to use.
That's why the goal is to have one config file with all settings for each project.
But first of all, docToolchain has to know where your documentation project is located.

If `docDir` is defined, the default for `mainConfigFile` is `Config.groovy` in the root folder of your `docDir`.

You have several options to specify the location of your documentation project (`docDir`) and the location of your config file (`mainConfigFile`).

=== Commandline

Specify the property on the commandline

    ./dtcw generateHTML -PmainConfigFile=Config.groovy

TIP: you can verify the location of your `Config.groovy` by executing docToolchain with the `--info` parameter which sets the loglevel to `info`.
It will print the location on the command line (among other settings)

=== Environment Variable

You can also specify the `mainConfigFile` using the environment variable `DTC_CONFIG_FILE`. This will override the default value of `docToolchainConfig.groovy`.

    export DTC_CONFIG_FILE=path/to/config.groovy

=== Automatic Config File Creation

If the config file does not exist, docToolchain will prompt you to create a default one. For unattended use (e.g., with CI/CD pipelines or LLM agents), you can enable automatic config file creation:

==== Using the DTC_HEADLESS Environment Variable

When `DTC_HEADLESS=true` is set, docToolchain will automatically create a default config file without prompting:

[source, bash]
----
export DTC_HEADLESS=true
./dtcw generateHTML
----

==== Using Project Property

You can also explicitly request automatic config creation using the `-PcreateConfig=true` property:

[source, bash]
----
./dtcw generateHTML -PcreateConfig=true
----

This is useful when you want to ensure a config file exists without enabling full headless mode.

=== dynamic configuration properties

Sometimes you need a more dynamic configuration.
Since the configuration file is an executable `.groovy` file, you can not only configure static values but also fetch dynamic once.

For example,

[source]
----
   example = System.properties.myProperty
----

You can then specify the property with the `-D` parameter like this

[source]
----
./dtcw docker generateHTML -DmyProperty=myValue
----

In the same way, you can use environment variables

[source]
----
   example = System.getenv("myEnvVariable")
----

But in this case, you have to ensure that the environment variable can be accessed.
It will not work for docker based execution of `dtcw`

=== Content of the `mainConfigFile`

[source,groovy]
----
include::{projectRootDir}/Config.groovy[tags=**]
----

== AsciiDoc config

== Command Line Parameters
