:filename: 025_development/040_debugging.adoc
== Debugging

include::../_feedback.adoc[]

Things not working as you expected? Here are some tips that might help you.

=== Environment

To get the best out of docToolchain, we recommend that you set up a development environment.
This way you get to see the inner workings and you also get to add extra debug output to the tasks that you want to inspect.

=== Task Output and Config

docToolchain v4 runs on the JVM and no longer uses Gradle, so there is no `--info` flag.
To find out what is going on, run the task with `./dtcw4 generateSite` and inspect the task output it prints to the console, together with your `docToolchainConfig.groovy` settings.

This shows the config settings as seen by docToolchain along with many other internal details.

=== Site Templates (GSP)

If something goes wrong with a template, you typically don’t receive much information about the problem. Take a look at `menu.gsp` to see how you can use `try/catch` blocks to get an error message. But to find out where the problem is occurring, you’ll need to use the poor man’s debugger and add some `System.out.println` statements. Make sure that you use the full `System.out.println` statement and not only `println` otherwise you won’t see any output.

=== Theming, Menu and Images

How the system creates the menu entries might seem like magic, but sometimes you cannot work out why an image is not shown. Remember, there is a way that you can check the generated files.

Check the `build/microsite/tmp` folder to see the folder that is fed into the site generator. In this folder, all files will have additional `jbake` attributes which are used to build the menu. They are generated from the original attributes of the file and folder/filename information. Now check the `build/microsite/output` folder to see the generated result. This often helps you find out where an image actually is located.

=== Script Execution Debugging

In docToolchain v4 the entry point is the `dtcw4` wrapper (the v3 launcher was `bin/doctoolchain`).
The execution of the link:../../../bin/doctoolchain[] bash script may be traced by setting the environment variable `DTC_BASH_OPTS` to, e.g., `-vx`.
